### PR TITLE
Specify which fields are allowed to be nested

### PR DESCRIPTION
**Pull request by felixbarny**
While `log.level` is not allowed to be nested (for example `"log": { "level": "INFO" } }`) due to readability concerns, the same is not true for other properties, such as `trace.id`.

### CODE REVIEW

**Review by Mpdreamz — CHANGES_REQUESTED** [review]
Since the default is nesting allowed. Can we rename this to `nesting_required`.

**Comment by felixbarny** [comment]
Maybe I changed it too quickly now. For `log.level`, it's not allowed to be a nested object, therefore `nesting_allowed=false`. I'm not sure the semantics are the same when saying `nesting_required=true` for `log.level`. As it's required *not*  to be nested.

For `trace.id`, for example, both the nested and the dotted version should be allowed. The spec always uses the dotted field names so that all properties are at the top level. But setting `nesting_allowed=true` signals that it's allowed to represent fields as nested objects in the log events.

So I propose we either leave it at `nesting_allowed` or call it `nesting_disallowed`. However, I prefer properties that don't contain negations in their name as it's easier to parse for my brain. For example, `nesting_disallowed=false` is a double negation and `nesting_allowed=true` is easier to understand.

**Comment by Mpdreamz** [comment]
If the property is omitted the default is `false`.   So I'm arguing the property is named so that the most common case is `false`. 

So maybe call it something completely different like `human_readable`. 

Human readable fields we prefer at the beginning and dotted but are allowed to appear nested too as long as they are only provided once?

**Comment by felixbarny** [comment]
> If the property is omitted the default is false. So I'm arguing the property is named so that the most common case is false.

Are you saying we should omit in on all properties aside from `log.level` to make it more concise? That makes sense, I think. We could also just define the default value of `nesting_allowed` as `true` and only set `nesting_allowed=false` for `log.level`.

I see that a default of `false` may be more intuitive. But I can't come up with a good property name for that.

As of now, I always specified `nesting_allowed`, unless the key is on the top-level, such as `@timestamp` where there's no ambiguity.

> So maybe call it something completely different like `human_readable`.

Imho, that doesn't immediately convey what it implies.

> we prefer at the beginning

That's already covered by the `index` property

> but are allowed to appear nested too as long as they are only provided once?

Could you clarify what you mean by that?
I'd argue that we should prefer `"log.level": "INFO"` over `"log": { "level": "INFO" } }`. It's shorter, easier to read and we already have other properties within the `log` namespace, such as `"log": { "origin": { "file": { "name": "..." } } } }`

**Comment by Mpdreamz** [comment]
> Are you saying we should omit in on all properties aside from log.level to make it more concise? 

Aye, atleast that if omitted it defaults to the right thing.

> That makes sense, I think. We could also just define the default value of nesting_allowed as true and only set nesting_allowed=false for log.level.

If you bind this to an object the default will be `false` so therefor designing for omission being `false` is easiest. 

> Could you clarify what you mean by that?
I'd argue that we should prefer "log.level": "INFO" over "log": { "level": "INFO" } }. It's shorter, easier to read and we already have other properties within the log namespace, such as "log": { "origin": { "file": { "name": "..." } } } }

Aye I meant that but e.g if a logger does not yet explicitly and they happen to come through as nested thats still okay.

> Imho, that doesn't immediately convey what it implies.

`prefer_as_field` `prefer_on_root`, `prefer_rooted` ? Naming... 😆

**Comment by felixbarny** [comment]
`top_level_field`?

**Comment by Mpdreamz** [comment]
❤️ :it:

**Comment by felixbarny** [comment]
Thanks for your input Martijn! If you're happy with the current state, could you approve the PR? Or is there anything else?

**Review by Mpdreamz — APPROVED** [review]

**Pull request merged**
