### PR TITLE
Overview docs

### LINKED ISSUE #31: Add ECS logging overview documentation
We have started to put the documentation for the individual loggers to the [elastic.co website](https://www.elastic.co/guide/en/ecs-logging/java/current/index.html).

Similar to the overview docs in APM, I think it makes sense that we have an overview page for ECS loggers that describe at a high level what ECS loggers are, what benefits they have, and link to the individual language loggers.

This can serve as a canonical page when linking from other parts of our docs, such as from the Filebeat docs.

I guess we could use some of the things that are written in the [overview page of the ecs-logging-java docs](https://www.elastic.co/guide/en/ecs-logging/java/current/intro.html). The question is if we want to duplicate some of the information, link to the generic overview docs, or have the docs for the individual loggers be sub-sections of the global docs. 

@bmorelli25 do you have an opinion on that?

### PR DESCRIPTION
**Pull request by felixbarny**
Preview of the setup page:

Screen Shot 2020-12-08 at 18 00 57

TODOs
- Release on elastic.co
- Remove [intro section of the Java logger](https://www.elastic.co/guide/en/ecs-logging/java/current/intro.html) in favor of this
- Remove step 2 (Enable APM log correlation) and step 3 (configure filebeat) of the [Java get started docs](https://www.elastic.co/guide/en/ecs-logging/java/current/setup.html#setup-step-2) in favor of this.
- Decide on how to include/link to the general into section from the individual loggers (so far [Java](https://www.elastic.co/guide/en/ecs-logging/java/current/intro.html) and [.NET](https://github.com/elastic/ecs-dotnet/pull/120))

Follow-ups for later

Getting started guides for more platforms, such as PCF, S3, CloudWatch, Azure, ...

closes #31

### CODE REVIEW

**Comment by bmorelli25** [comment]
> Decide on how to include/link to the general into section from the individual loggers (so far Java and .NET)

As discussed in https://github.com/elastic/ecs-logging/issues/31, since we can't have one ECS doc book to rule them all (due to varying versioning), my initial thought was to add include statements to this content and include it in each agent's ECS docs. If we go this route, I don't think we need to build an ecs-logging book. We'd only build the agent books, and each would pull in the shared content from this repo. In this scenario, it's probably easiest to just merge this PR and https://github.com/elastic/ecs-dotnet/pull/120, and let me set everything up in follow-up PRs

**Comment by felixbarny** [comment]
After you approve this PR, feel free to merge it and proceed with the follow-ups. Thanks 🙂

**Comment by felixbarny** [comment]
Is it feasible to include the Filebeat setup guide (step 3) from the overview docs into the [logger setup guides](https://www.elastic.co/guide/en/ecs-logging/java/current/setup.html#setup-step-3)? If not, linking to them should be good enough.

**Comment by bmorelli25** [comment]
> Is it feasible to include the Filebeat setup guide (step 3) from the overview docs into the logger setup guides? If not, linking to them should be good enough.

Yes, that is possible.

**Review by bmorelli25 — APPROVED** [review]

**Pull request merged**
