### PR TITLE
Update README.md

### LINKED ISSUE #4: Serilog
provide ECS formatter for Serilog. 

pinging @Mpdreamz, @russcam & @codebrain

### PR DESCRIPTION
**Pull request by codebrain**
Add .NET links

### CODE REVIEW

**Comment by philkra** [comment]
I didn't see this PR, already out in the changes, sorry!

**Review by philkra — CHANGES_REQUESTED** [review]
Please add a new section called `Enrichers` for APM log enrichment for NLog and Serilog. Same for the benchmarking enricher.

**Comment by philkra** [comment]
ping @codebrain

**Comment by codebrain** [comment]
Hey @philkra - I have added the sections for APM and Benchmarking

**Review by philkra — APPROVED** [review]
LGTM

**Comment by codebrain** [comment]
@philkra - I don't seem to have write access to this repo to merge in. Would it be possible to merge or grant access? Thanks!

**Pull request merged**
